components/About.js
components/Join.js

Just some random grammar fixes.

Grammatical fixes

---

pages/_app.js
pages/_document.js

Not 100% sure if this works (I don't know react!) but I think it does fix 2 a11y issues

A11y fixes

---

pages/index.js

Removed parent <div> which was causing scroll without any content, using fragments instead.

Removed excess scrollbar

---

pages/_app.js
pages/index.js

Hi, 
Hope this helps. I am quite new to open sourcing. 
I have added overflow-hidden to the layout component in index.js. 
The only other way that I know off the top of my head to have similar positioning, is to use position absolute on the image however then we would need to give the image it's own scaling properties and it won't be able to depend on the Tailwind container class as it is now.
regards,

horizontal-scrolling

---

components/Header.js

Fix for #34.
Sorry for reopening the PR, made a mistake in my fork.

Added `noopener noreferrer` to external links;

---

README.md

Update banner size

---

README.md

Misc spelling and grammar fixes

---

components/Hero.js
components/Old_Join.js

I raised the PR for discord widget. I used @zhorton34's PR since he was not replying for long and his PR had conflicts. This was an important feature. 
We can add up more issues upon this now for Hacktoberfest. 
@avneesh0612 review this PR. Since it is mine, I should not review and merge it.

added the discord widget using zhortons code

---

README.md

Update README with Contributing and License

---

components/Header.js
package-lock.json

Hi sir,
I have changed contributors from plain text to a button. Please accept my PR for Hacktoberfest.
Reagrds
GeorgeET15

Contributor text changed to button :)

---

components/Contributors.jsx

Edit Contributors heading level

---

components/Contributors.jsx
components/ProfileCard.jsx

Hi!
This is a small pull request to fix two errors regarding missing keys on the Contributors page.
I also took the liberty to suggest a refactor on the Social Links to allow it to be more dynamic, changing the switch/case statement for a simple object approach.
Let me know what you think!

Fix React missing "key" errors on Contributors page

---

components/Contributors.jsx
pages/contributors.js

Issue #79 
Duplicate main element removed from contributors page and some moved some styling up to the parent.

Duplicate main elements removed from contributors page.

---

.github/ISSUE_TEMPLATE/bug_report.md

add bug-report issue template

---

components/ProfileCard.jsx

fix accessibility issue related to social icons

---

pages/_app.js
pages/_document.js
utils/gtm.js

feat: added google analytics via tag manager

---

.github/ISSUE_TEMPLATE/bug_report.md
components/Hero.js

Img overlap with contrib

---

components/Contributors.jsx
components/GetContributors.js
components/Sponsors.js

fixed the bug in the page of contributors in the sponsors

---

components/Header.js

removed the button of contributors in the page contributors

---

components/Header.js
components/Main.js
pages/_app.js
public/manifest.json

removed white vertcal line

---

.gitpod.yml

Created gitpod

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

👍 create a custom pull_request_template file in the .github folder in the main branch for the PR.

add pull_request_template.md file in the .github folder.

---

components/Main.js
content/homepage.js
package-lock.json
yarn.lock

Issue Link: https://github.com/FrancescoXX/4c-site/issues/155

✨ Add twitter link on homepage

---

components/Contributors.jsx
components/Header.js
components/Layout.js
components/Main.js
components/ProfileCard.jsx
content/homepage.js
package-lock.json
pages/contributors.js
pages/index.js
styles/global.css

- add custom color (.bg-theme) in global.css
**homepage**
- change background 
- change font color 
- change button color and add hover effect
**contributors page**
- change background
- change font color
- change social icons color
Please review my PR, thank you!

update website color palette

---

.github/ISSUE_TEMPLATE/doc_issue.yml
.github/ISSUE_TEMPLATE/features.yml

fixes #147
added feature and docs issues template
`don't know why pull request template wasn't working`

add more issue templates

---

content/contributors.json

🚀 🚀 Add Tobiloba to the Contributors page

Add Tobiloba

---

styles/global.css

💯 🚀 Fixed the WCAG mobile view problem by adding media queries.

Mobile view accessibility fixed

---

components/Header.js

Improvement: Less gap between elements of header.

---

CONTRIBUTING.md

**Description:**
Updated the hyperlink to CODE_OF_CONDUCT.md in contributing.md file and tested in local
**Issue:** #189 
**Screenshot:**
Appreciate that!

Update CODE_OF_CONDUCT hyperlink

---

components/Header.js

add project button

---

components/Header.js

changed the logo which solves https://github.com/FrancescoXX/4c-site/issues/178 issue. after new logo

update the new logo

---

BRAND.md

Add Brand file and add brand palette color #221

---

BRAND.md

Added font

---

components/Contributors.jsx
components/Header.js
components/Layout.js
components/Main.js

Navbar movement issues and logo routing fixed

Navbar movement issues and logo routing fixed

---

components/Header.js

this merge will solve https://github.com/FrancescoXX/4c-site/issues/208 issue

updated navbar contributor to active members

---

pages/Faq.js
pages/projects.js

Description:
Coming soon page added for FAQ and Project pages
Issue- #219 
Screenshot:

Coming soon page added

---

components/Header.js

Description:
Updated the navbar with so that github button wont come to next line
Issue: #242 
Screenshot:

Navbar width fixed

---

components/Contributors.jsx
components/Header.js

Fixed the Contibutors page header

Fixed the Contibutors page header

---

PROJECTS.md

I just noticed the Becca Lyria twitter handle was wrong in PROJECTS.md :)

fix Becca Lyria twitter handle

---

README.md

Updated line 1 on readme.md from # 4C to #4C (The Cool Community of Content Creators)

updated the title

---

PROJECTS.md

- Added project Milan to the list
- Checkout project Milan [here](https://github.com/IAmTamal/Milan)

feat : Add Tamal's project to the list 🛠

---

content/faq.json
package-lock.json
pages/Faq.js

FAQ page structure is done.
Created a faq.json file in "content" folder. Then fetch it to faq page
Sreenshot:

 [FEATURE] FAQ page structure done

---

components/ActiveMembers.js
components/Header.js
pages/activeMembers.js

Description:
Contributors name change to Active members in all label and code
Issue: #208

Active member name changed

---

components/Header.js

Closes #217 
Added a blog button to the website header and linked it to the blog page

feat: added blog button to header

---

content/projects.json

made a file projects.json which took in all the projects that were in [PROJECTS.md](https://github.com/FrancescoXX/4c-site/blob/main/PROJECTS.md).
There is a name, title, description, link (GitHub), and a Twitter handle for each object.

added projects.json

---

content/faq.json

I added more questions to the FAQ page. There is a need to embed the link to the contribution guidelines on the last FAQ page but I am not so sure how to do that with JSON data.

Add FAQ content

---

components/Header.js
content/faq.json
content/projects.json

The issue was caused by unformatted files; fixed by running npm run format. 
npm run format:check
```
> format:check
> prettier --check "{components,content,docs,pages,styles,utils}/**/*.{js,jsx,ts,tsx,css,scss,json,yaml,md}"
Checking formatting...
All matched files use Prettier code style!
```

formatted files - format check passed

---

components/Footer.js
components/Layout.js
components/Main.js
content/faq.json
content/projects.json
pages/faq.js
pages/videos.js

YouTube video
Footer Position
FAQ font size

Fixed issues: #291

---

CHANGELOG.md
README.md
package.json

Closes #263 
Added fork instruction to README, and rephrased the section concerning addressing errors.

docs: updated README to have fork instruction

---

components/Header.js
package-lock.json

Resolved Issue of Mobile View Navigation Bar

---

components/FaqAccordian.js

pull update from upstream, reopening PR for issue #318

decrease width of the accordion component on mobile

---

pages/activities.js

activities mobile view problem solved issues: #325

activities mobile view problem solved issues: #325

---

components/FaqAccordian.js
pages/faq.js
styles/details.css
styles/global.css

:wheelchair: Improve FAQ page accessibility.

---

components/GetProjects.js
content/projects.json

closes #333 
we added a key-value in the projects.json file with a new key: screenshot

add the img for the projects

---

content/projects.json

Add Tobi's portfolio image

---

content/projects.json

chore: updated my project preview

---

content/projects.json

Description:
Added my new project `TailwindCSS Bootstrap` in project.json

Added Tailwindcss bootstrap project

---

components/ActiveMembers.js
components/FaqAccordian.js
components/GetProjects.js
components/Header.js
components/Main.js
components/ProfileCard.jsx
package-lock.json
pages/blog.js
pages/faq.js
pages/videos.js

I just made the design changes we approved in the Discord server, made changes for the navbar, project cards in projects page, active members styles and alignmet in main page.

Feat:design changes done

---

CHANGELOG.md
components/GetProjects.js
package-lock.json
package.json

Closes #353 
- added extra link for `live website`

[FEAT] updated project card layout

---

content/projects.json

I fixed the issue of the image of my project on the Projects page and it looks much better now.

Fix Tobiloba Image

---

components/BlogCard.js
components/GetProjects.js
content/blog.json
package-lock.json
pages/blog.js

blog card added. add blog details in content/blog.json

Blog Card Added issues #164 & projects card space #358

---

components/GetProjects.js

Some issues regarding the project cards have been fixed. However, regarding the varying heights, what can be done is to ensure that all the images have the same aspect ratio

Fix some issues on the project cards

---

components/GetProjects.js
package-lock.json

I fixed the huge gap between the columns of the cards on the projects page.

Fix project cards

---

content/homepage.js

small typo adjustment

---

content/projects.json

Added Free Frontend Resources to `project.json` file.

feat: add free frontend resources project

---

components/Header.js
content/navbar.json
content/projects.json

I replaced the buttons for navigations with the "a" tags and represented the buttons on the nav as an array of objects that I'm mapping over.
Fixes issue #220

fix accessibility issue of navbar buttons

---

components/Header.js
components/Main.js
tailwind.config.js

Improved mobile view of main page

---

components/GetContributors.js
components/ProfileCard.jsx
content/contributors.json

add linkedin to the profile cards

---

CHANGELOG.md
components/GetVideos.js
content/videos.json
package-lock.json
package.json

Fixed Videos embedding style

---

components/Header.js

fix navigation style on tablet view

---

CHANGELOG.md
components/GetVideos.js
content/videos.json
package-lock.json
package.json

Reverts FrancescoXX/4c-site#400

Revert "Fixed Videos embedding style"

---

components/GetVideos.js
content/videos.json

[Screencast from 02-12-2022 22:05:43.webm](https://user-images.githubusercontent.com/96334363/205386044-742e4fc0-bed7-465c-86a1-17478619d9c3.webm)

fix video page layout

---

components/BlogCard.js
components/Header.js
styles/global.css
tailwind.config.js

Fix Blog Cards issues 

---

components/GetProjects.js

fix misaligned text on project card

---

components/Footer.js
package-lock.json

Add LinkedIn icon in footer

---

components/Header.js
styles/global.css
tailwind.config.js

improve the responsive menu UI and some code improvement
from this
to this !!

:lipstick: fix responsive menu breakpoint 

---

components/BlogCard.js
package-lock.json
package.json
tailwind.config.js

Add blog string truncate

---

README.md

Add readme update

---

components/Header.js
package-lock.json

changed a tag to link

---

components/GetProjects.js
components/Header.js

Add UI fix in projects page

---

components/GetProjects.js
components/Header.js

Reverts FrancescoXX/4c-site#423

Revert "Add UI fix in projects page"

---

components/GetProjects.js
components/Header.js
package-lock.json

Hello Tobi, Please look on this.
Tried to fix

Responsive

---

components/GetProjects.js

new tab open issue #426 solved

---

components/Header.js
tailwind.config.js

Beforeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
Afterrrrrrrrrrrrrrrrrrrrrrrrrrrrr
added a little bit of shadow🧟‍♀️ you can barely see it🤌🏻

navbar improved

---

content/homepage.js
styles/button.css

New Contributor Alert🚨
Hi there, just looked up your website, great work firstly, it looks amazing. Love how it's maintained by the community.
I noticed that the _Follow on Twitter_ button was coloured Violet (the Discord Brand colour) on hover.
I thought of making a minor adjustment, so I created a similar `btn` class for the _Follow on Twitter_ button with the classic Twitter Blue background on hover. 
Hope this helps, wish you a good day :)

✨ Blue Bg on hover for "Follow on Twitter" Button

---

components/GetVideos.js

… in videos pages
items are rendered successfully but getting "each child in a list ....." error in the terminal.
fix it by added key, index

 :rotating_light: Fix the 'each child in a list should have a unique key console error'

---

components/GetStaff.js
components/ProfileCard.jsx
components/Staff.js
content/navbar.json
content/staff.json
pages/staff.js

Add Staff Page

---

components/GetVideos.js
content/videos.json

Improve the Videos page
from this
to this

:pencil2:improve the video component 

---

components/BlogCard.js

fix transition issue in blog cards

---

components/ActiveMembers.js
components/BlogCard.js
components/GetVideos.js
components/GoToTop.js
components/Header.js
components/Main.js
components/Staff.js
content/blog.json
package-lock.json
package.json
pages/active-members.js
pages/activities.js
pages/blog.js
pages/faq.js
pages/index.js
pages/joinourteam.js
pages/projects.js
pages/staff.js
pages/videos.js

resolves #448 
resolves #451 
resolves #432

Add container in website pages

---

components/ActiveMembers.js
components/GetProjects.js
components/GetVideos.js
components/Main.js
components/Staff.js
tailwind.config.js

HIi Tobi, now for container, I've make seperate variable in taiwing config file for container. In future whenever we want to change container size, we can change at only one place and changes will reflect to evrywhere in our website:)

Structure changes

---

content/activemembers.json

updated - profile added

---

components/ActiveMembers.js
components/BlogCard.js
components/FaqAccordian.js
components/Footer.js
components/Form/JoinUsForm.js
components/GetProjects.js
components/GetVideos.js
components/Header.js
components/JoinOurTeam.jsx
components/Layout.js
components/Loading.jsx
components/Main.js
components/ProfileCard.jsx
components/Staff.js
components/Users.js
content/activemembers.json
package-lock.json
package.json
pages/activities.js
pages/blog.js
pages/faq.js
styles/button.css

Fix Desktop Navbar and Linting issue

---

components/GetVideos.js
content/videos.json

video card design

---

components/GetVideos.js
content/videos.json

Reverts FrancescoXX/4c-site#456

Revert "video card design"

---

components/GetVideos.js

video card design improved
***width problem solved
issue #456

video card design improved

---

components/ActiveMembers.js
components/GetProjects.js
components/GetVideos.js
components/Header.js
components/Staff.js
pages/blog.js
pages/faq.js
styles/details.css

navbar padding decreased for sm device

---

components/Header.js

There was an issue where the navbar wasn't vertically aligned with the main content. This is a fix for the issue

Fixed issue #463

---

components/ActiveMembers.js
components/GetProjects.js
components/GetVideos.js
components/Staff.js
components/Title.js
pages/activities.js
pages/blog.js
pages/faq.js

Add reusable header title

---

content/videos.json

new livestream video added | issue #475

new livestream video added | issue #475

---

components/Header.js

The first change was regarding the class order warning. There were warnings in VSCode with the class order and was fixable by rearranging them. 
The next change is the change of color in the hamburger icon from black to white to match the theme

Arranged classes and made the hamburger icon white color for mobile

---

components/Header.js

prettier formatting error solved issue #

prettier formatting error solved

---

README.md

 Included Formatting Check and Linting cmd

---

content/activemembers.json

Updated my section in [activemembers.json](https://github.com/FrancescoXX/4c-site/blob/main/content/activemembers.json)

Updated AryanBabber section 

---

components/GetProjects.js

all project card are center aligned issue #491

all project card are center aligned issue #491

---

README.md
components/GetProjects.js

formatting issue fixed

---

components/GetProjects.js
components/Header.js

<h3>Before changes</h3>
<h3>After changes</h3>

Hover Effect Added

---

components/ActiveMembers.js
components/BlogCard.js
components/FaqAccordian.js
components/Footer.js
components/Form/JoinUsForm.js
components/GetProjects.js
components/GetVideos.js
components/Header.js
components/JoinOurTeam.jsx
components/Layout.js
components/Loading.jsx
components/Main.js
components/ProfileCard.jsx
components/Staff.js
components/Title.js
components/Users.js
pages/faq.js

I fixed these with the commands "npm run format" and "npm run lint". I checked "npm run format:check" and "npm run lint:check"

fix formatting and linting issues

---

README.md
components/GetProjects.js
package-lock.json
styles/global.css
tailwind.config.js

project page break issue resolved (pandemic #501 is gone)

---

README.md
components/GetProjects.js
components/Header.js
content/projects.json
content/stacks.json

Added a filter in the Projects section which allows people to filter out the projects as per their liking and start contributing.
Here's the list of changes made in this PR:
* Readme.MD:
* Added stack key in the project example
* GetProjects:
* Added the filter part
* Header.js:
* Removed a commented line which meant nothing
* projects.json:
* Added stack key in all the projects
* Added stacks.json to make a list of available stacks

Fixed issue #488 and #489 | Added Project filter

---

README.md
components/GetProjects.js
components/Header.js
content/projects.json
content/stacks.json

Reverts FrancescoXX/4c-site#522

Revert "Revert "Fixed issue #488 and #489 | Added Project filter""

---

package.json

added npx to resolve format issue

---

package.json

Reverts FrancescoXX/4c-site#525

Revert "added npx to resolve format issue"

---

.eslintrc
components/ActiveMembers.js
components/BlogCard.js
components/FaqAccordian.js
components/Footer.js
components/Form/JoinUsForm.js
components/GetProjects.js
components/GetVideos.js
components/Header.js
components/JoinOurTeam.jsx
components/Layout.js
components/Loading.jsx
components/Main.js
components/ProfileCard.jsx
components/Staff.js
components/Title.js
components/Users.js
package-lock.json
package.json
pages/faq.js

What we were using:
https://www.npmjs.com/package/eslint-plugin-tailwind
What I replaced it with:
https://www.npmjs.com/package/eslint-plugin-tailwindcss
Reasoning: 
The newer package is more maintained and works nicely with our Prettier Config.

Switched ESLint Plugin for TailwindCSS

---

components/GetProjects.js
package-lock.json
package.json

Add dropdown in projects

---

components/Footer.js
components/GetProjects.js

fix footer year

---

components/Header.js
next.config.js
package-lock.json
package.json

This commit updates all dependencies of the project and also update the React and Next JS Versions to the latest one with all changes in the files necessary done

 #512 Complete [Upgrade Complete]

---

components/BlogCard.js

fixed the card width of the blog card in smaller screens
Old:
New:

fixed issue #545

---

4c.config.js

logo link in `4c.config.js` is modified to fix issue #544

updated the logo link as per issue #544

---

components/Header.js
package-lock.json

I only replace the one in header, and not the rest because their source domain can be dynamic.

Replaced <img> with next/Image

---

components/Header.js
content/projects.json

Fix Accessibility Issue on the Hamburger Button

---

components/Header.js

Reverts FrancescoXX/4c-site#576

Revert "Fix Accessibility Issue on the Hamburger Button"

---

src/components/GetProjects.js
src/components/Header.js

Fix search input in projects page and Accessibility issue in hamburger button

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/other.yml

Add issue template other (resolves #597)
Disable empty issues (resolves #598)
Add link to discussions in issues selector (resolves #599)
Add link to discord community in issues selector (resolves #600)

GitHub Magic B, Annexure II

---

README.md

fixes #614 
Note: I think taht having these files nested into a directory might confuse people not finding them in the root folder.

Contributing links fixed

---

src/components/GetProjects.js

I have used JavaScript Set object and destructuring in order to keep only unique values in filteredProjects state.

Bug-Fix-Repeating-Projects-#605 

---

src/components/ProfileCard.jsx
src/components/SocialLink.jsx

Fixed issue #630 UI changes in active members and staff

---

src/components/GetProjects.js

delete one title from projects page issue #633

---

src/components/GetVideos.js

Fix card height bug in the videos page

---

src/data/videos.json
yarn.lock

4Castle event added to videos.json file
resolve #643

refactor: 4castle video added

---

.vscode/settings.json
src/components/GetActivities.js
yarn.lock

activities card design improved and card fixed
issue #645

fix: activities card design improved and card broke fixed

---

README.md

@tobySolutions I have corrected the error
Fixes #647

Discord and Twitter links embedded correctly

---

src/components/GetActivities.js

activities card width fixed for md lg xl device

fix: activities card width fixed for md lg xl device

---

src/components/GoToTop.js
src/pages/_app.js
src/pages/active-members.js
src/pages/activities.js
src/pages/blog-posts.js
src/pages/faq.js
src/pages/index.js
src/pages/joinourteam.js
src/pages/projects.js
src/pages/staff.js
src/pages/videos.js

structure changes and GoToTop button's background changed
resolves #650

refactor: structure changes

---

src/data/activemembers.js
yarn.lock

Fix the sorting mechanism and algorithm

fix(activemembers.js): fix

---

src/components/Main.js
src/data/homepage.js

**This PR closes #662**
- In Mobile view the home page is all aligned to the left, as a result there was massive gap, wastage of space.
- The code for the `The Cool Community of Content Creators` text is splitted in a not so good way, as there were use of multiple `span`,  `divs`
- I need to remove some extra code and made it mobile responsive.
- I will be changing some stylings, so that the extra gaps, left alignment would change for mobile view (screenshot below)
**Screenshots ( After, Before) :**

[FEAT]: Refactored home page

---

src/components/CommunityPartners.js
src/components/Main.js
src/data/partnerCommunities.json

resolves #664 
This PR add new section "Community Partners" to home page end.

refactor: add community partners to home page

---

src/components/FaqAccordian.js

fix(bug): fixed faq accordion answer not taking entire width

---

src/components/Header.js
yarn.lock

I was able to fix the scrollable sidebar issue I raised earlier

scrollable sidebar fixed

---

CODE_OF_CONDUCT.md

Things added/changed:
- Update the CoC to the latest version.

chore: update the CoC to the latest version

---

src/components/Header.js
yarn.lock

feat: add background for navbar

---

src/components/Header.js
yarn.lock

Reverts FrancescoXX/4c-site#680
The background breaks on desktop screens

Revert "feat: add background for navbar"

---

src/components/ActiveMembers.js
src/components/GetProjects.js
src/components/Staff.js
yarn.lock

Fixes issue #679 
Enhancing search bar UI of active and staff members page.
Enhanced search bar UI

fix(ui): enhanace search bar UI

---

src/data/projects.json

chore: update project data

---

src/data/projects.json

Right now, the repository is private and it will be public soon.

Update projects.json - Ali Reza

---

src/components/GetProjects.js
src/styles/global.css

Issue #702. Styled the search tab to match the design theme of the website. 
Now all three main pages have consistent search tabs.
*Before:*
*After:*
Please let me know in case you want me to change anything or in case of any feedback 😄

fix(search-tab): Improved search-tab of the projects page

---

src/components/GetProjects.js
yarn.lock

issue #703 Search icon is added in the project section search bar.
Before: 
After:

fix: search icon added in projects search bar

---

src/components/GetProjects.js
src/styles/global.css

References issue #704
Implemented the suggestions specified in the issue. Noq,
- The input box content has some margin
- The box is of consistent height throughout
- The search tab is made mobile-friendly
And solved the issue of search-icon misplacement in mobile-devices
Screenshots:

fix(search-tab): improved user experience and icon-positioning issue in search-tab of projects page

---

.github/workflows/json-check.yml

ci: Create json-check.yml

---

.github/workflows/greetings.yml

ci: Create greetings.yml

---

CONTRIBUTING.md

Update link for Byzanz Gif tool in CONTRIBUTING.md

---

src/components/Header.js

reduced the padding of the header from 1.4 rem to 0.7 rem.
Resolves #723

bug:reduced the notch padding

---

src/components/GetActivities.js
yarn.lock

Fixed activities section too close to the section before it
Description
The activities section of the website on the homepage is too close to the section before it on the homepage. A bit of spacing will be required to move it down a bit, thereby giving the homepage a better look.
Fix: Added a margin-top of 50px to push the activities section down a bit.
Resolves #722 @tobySolutions

fix: activities section a bit far from previous section

---

src/components/Header.js

@tobySolutions I made the changes
Resolves #724

fix: centered the menu-item!

---

src/components/FaqAccordian.js
src/styles/global.css

I have made the code changes for the PR #735 
Thanks,
Yokesh.
Resolves #735

Arrow dropdown patch 1

---

src/4c.config.js
src/components/Layout.js

Fixed #745 
Changed og image url with `https://www.4c.rocks/_next/static/media/logo.9b920fc5.png`

fix: og image url

---

src/components/GetActivities.js
src/components/GetVideos.js
src/components/Header.js
src/components/Main.js
src/components/blog-posts.js
src/components/faq.js
src/data/homepage.js
src/data/navbar.js
src/pages/_document.js
src/pages/index.js
src/styles/global.css
yarn.lock

fix: user interface

---

src/components/GetActivities.js
src/components/GetVideos.js
src/components/Header.js
src/components/Main.js
src/components/blog-posts.js
src/components/faq.js
src/data/homepage.js
src/data/navbar.js
src/pages/_document.js
src/pages/index.js
src/styles/global.css
yarn.lock

Reverts FrancescoXX/4c-site#754

Revert "fix: user interface"

---

src/components/Header.js

Improved UI consistency by modifying the button styling in the header component.

feat:improved UI consistency

---

src/components/Staff.js
src/utils/filterUsers.js

Feature added
- Improved on the search function to filter staff by name and description
Filtering by name
Filtering by description

feat: Filter staff by name and description

---

package.json
yarn.lock

Added support for commitizen plugin - https://github.com/commitizen/cz-cli, and made the repository commitizen friendly.
Fixes #782

feat: commitizen cli

---

src/components/Header.js

Resolves Issue #744
Changed the blurriness of the navbar

[fix]: blurness of Navbar
