FrancescoXX/4c-site

components/Hero.js
In this PR, I have taken care of #42. 
**Before**
**After**
=> fix: text overlap with nav area

.husky/pre-commit, package.json, yarn.lock
Installed `husky` and added a `pre-commit` hook to auto-format files so that they don't break workflows.
Here's it in action 👇 
.
Fixes #49
=> added pre-commit with husky to automate formatting files.

CONTRIBUTING.md
This PR adds contributing guidelines from my [community-health](https://github.com/SiddharthShyniben/community-health)
_**Don't merge it yet!**_ The contributing guidelines have been left very vague on purpose. I have added a lot of comments explaining and removing stuff which don't make sense at all. I'm not sure what the 4C site will do in the future, this is why I decided to keep it so.
Read through the file, follow the instructions, and tell me what I should change (or change it yourself!)
=> Add (very vague) contributing guidelines.

scripts/update_contributors.js
The contributors script breaks for users with no display name. This PR fixes that.
=> Fix contributors script

components/ProfileCard.jsx
Blog URLs on the contributing page had undefined (look bottom left of image).
Blog URLs can now be formatted as a proper link containing `http://example.com` or without such as `example.com`
=> Blog URLs had undefined and wouldn't work

pages/_document.js
Simple fix for the website overflow that is being caused by the image transform on some screen sizes.
**Before:**
**After:**
=> fix: horizontal overflow

components/Header.js
I aligned all the header items to flex-start so the huge button won't shift the header's layout
=> fix inconsistent gap in header

components/Header.js
Fixed Bug: There was a gap on the right on screens with a width less than ~380px.
=> fix: unwanted right gap on small screen

components/Footer.js
This PR adds visually hidden (with Tailwind's ``sr-only`` class) labels to the footer links, so they can be understood in a screen reader context.
Discord link example:
**Before**
**After**
=> Improve footer links accessibility

components/GetProjects.js
Fix Overflow on Desktop view. The scroller on the side is now gone.
=> Fix overflow on desktop view

components/Footer.js
I set the footer anchor tags` target attribute to blank, to ensure the offsite links are opened in a new  window tab
=> Set footer anchor tags target attribute to _blank

src/components/GetProjects.js
Not all projects in "data/projects.json" have stack array included, therefore I used optional chaining so the includes method can work properly.
=> Bug fix for GetProjects.js

src/components/Header.js, src/styles/global.css
https://user-images.githubusercontent.com/93247057/212470016-898208bd-bf24-4806-9b2e-824715a789a6.mp4
https://user-images.githubusercontent.com/93247057/212470043-552cb451-f407-4e48-bf95-3b4b8485cc19.mp4
Here I added some external CSS properties for the 4c ​​logo image. Although this is not a good solution but it works perfectly.
=> Add some 4C Logo property for prevent the up and down moving issue.

src/components/BlogCard.js, src/components/GetActivities.js, yarn.lock
- Closes #660 
- Fixed blog card overflow height issue. Made the height to `480px`. 
- Activity card overflow issue. 
- We were using `p` and `h6` tag and then also complicatedly using `flex` to keep them aligned. As a result in some screen sizes or when the content size incrreased the cards broke.
- Currently i have used `p` and `span` with appropriate stylings which serves the same purpose, and is better fitted.
**Previously :** 
**Current :**
=> [FIX] : Responsiveness bug fixes for cards

CONTRIBUTING.md
before: "First of ..."
after: "First of all, ..."
closes #674
=> Typo in docs - Contributing Guidlines Fixed

src/components/GetVideos.js
video card title padding, image border radius changed
Resolves #686 
before:
this PR close issue #686
=> [style]: video card design

src/components/Footer.jsx, src/components/GoToTop.js, src/styles/global.css
Fixes issue: #700 
- Now when the width of the screen is less than 400px, the back-to-top button fixes its position whenever the footer is visible (i.e, in the scope of the current window), such that it does not overlap the footer icons. (Please refer to the image below for reference)
- Added some media queries to fix the position of the button from the right, to suit mobile-devices
*Before:*
*After:*
*Demo Video:*
https://user-images.githubusercontent.com/71211731/223689873-9b0a7358-8ed4-4e47-ba9d-3e3c06da770e.mp4
Please let me know if you want me to make any further changes or in case of any feedback, thanks!
=> fix(Back To Top Button): Solves back to top button overlapping footer icons in mobile-devices

src/components/ProfileCard.jsx, src/styles/global.css
Issue: #738 
I have added a CSS animation to the profile bio text, which resolves the issue of text overflow on the profile card. By using this animation, the bio text now moves from right to left, allowing the user to read the entire bio without it being cut off.
To implement this solution, I modified the CSS for the bio text and added the animation property. I tested the animation on different browsers and devices to ensure it works correctly and does not impact the performance of the feature.
A screenshot of the profile card with the updated bio display is attached to the Pull Request, which clearly shows the animation in action
=> [FIX]: Resolved profile bio overflow issue with CSS animation

.github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/other.yml
This pull request fixes the syntax errors in the issue templates mentioned in Issue #747 . Specifically, the `documentation.yml`, `feature_request.yml`, and `other.yml` templates were not working due to YAML syntax errors.
I have corrected these errors by reviewing the YAML code and identifying and fixing any syntax mistakes. With these fixes, contributors can now use these templates to submit issues in a standardized and consistent format.
=> [Fix]: Issue Templates Syntax Errors

src/data/projects.json
Change of domain for Open Source With Pradumna project. It has been migrated  from **oswp.study** to **os.pradumnasaraf.dev**
=> chore: update my project domain

src/components/GetActivities.js
This PR fixes the image in the activities section that looks bad on the live site
Before:
After:
=> fix: image in activities
